<?xml version="1.0"?>

<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Include Gazebo Parameters -->
  <xacro:include filename="$(find robot_description)/urdf/robot_gazebo.xacro" /> 
  <!-- Include ros2_control Plugins -->
  <xacro:include filename="$(find robot_description)/urdf/robot_ros2_control.xacro" />


  <!-- Chassi properties -->
  <xacro:property name="chassis_diameter" value="0.14"/>
  <xacro:property name="chassis_radius" value="${chassis_diameter/2}"/>
  <xacro:property name="chassis_thickness" value="0.008"/>
  <xacro:property name="chassis_distance_from_floor" value="0.033"/>
  <xacro:property name="chassis_mass" value="8.2573504E-01"/>
  <!-- Chassi moment of inertia -->
  <xacro:property name="chassi_Ixx" value="2.2124416e-02"/>
  <xacro:property name="chassi_Iyy" value="2.1193702e-02"/>
  <xacro:property name="chassi_Izz" value="2.0064271e-02"/>
  <xacro:property name="chassi_Ixy" value="-1.2294101e-04"/>
  <xacro:property name="chassi_Ixz" value="3.4938785e-04"/>
  <xacro:property name="chassi_Iyz" value="-5.0120904e-05"/>
  <!-- Wheel properties -->
  <xacro:property name="wheel_sphere_diameter" value="0.066"/>
  <xacro:property name="wheel_sphere_radius" value="${wheel_sphere_diameter/2}"/>
  <xacro:property name="wheel_translation" value="0.03"/>
  <xacro:property name="wheel_mass" value="0.0530086090966721"/>
  <!-- Wheel moment of inertia -->
  <xacro:property name="wheel_Ixx" value="1.8792911368909E-05"/>
  <xacro:property name="wheel_Iyy" value="3.11510738759073E-05"/>
  <xacro:property name="wheel_Izz" value="1.88266886146847E-05"/>
  <xacro:property name="wheel_Ixy" value="3.31256392204584E-10"/>
  <xacro:property name="wheel_Ixz" value="-1.14082001662767E-08"/>
  <xacro:property name="wheel_Iyz" value="-3.60499245082192E-10"/>


  <!-- Degrees to radians-->
  <xacro:property name="deg2rad" value="${pi/180}"/>
  <!-- Meters to centimeters -->
  <xacro:property name="cm2m" value="${1/100}"/>


  <link name="base_footprint"/>


  <!-- Chassi -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://robot_description/meshes/base_link.STL" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://robot_description/meshes/base_link.STL" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.04" rpy="0.0 0.25 0.3" />
      <mass value="${chassis_mass}"/>
      <inertia ixx="${chassi_Ixx}" ixy="${chassi_Ixy}" ixz="${chassi_Ixz}"
               iyy="${chassi_Iyy}" iyz="${chassi_Iyz}"
               izz="${chassi_Izz}" />
    </inertial>
  </link>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 ${chassis_distance_from_floor}" rpy="0 0 0"/>
  </joint>


  <!-- Right wheel-->
  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="${90*deg2rad} 0 0" />
      <geometry>
        <mesh filename="package://robot_description/meshes/wheel_right_link.STL" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 -${wheel_translation} 0" rpy="${90*deg2rad} 0 0" />
      <geometry>
        <sphere radius="${wheel_sphere_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 -0.014 0" rpy="0 0 0" />
      <mass value="${wheel_mass}" />
      <inertia ixx="${wheel_Ixx}" ixy="${wheel_Ixy}" ixz="${wheel_Ixz}"
               iyy="${wheel_Iyy}" iyz="${wheel_Iyz}"
               izz="${wheel_Izz}" />
    </inertial>
  </link>
  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link" />
    <child link="wheel_right_link" />
    <origin xyz="0 -0.07 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>
  

  <!-- Left Wheel-->
  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="${-90*deg2rad} 0 0" />
      <geometry>
        <mesh filename="package://robot_description/meshes/wheel_left_link.STL" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 ${wheel_translation} 0" rpy="${-90*deg2rad} 0 0" />
      <geometry>
        <sphere radius="${wheel_sphere_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0.014 0" rpy="0 0 0" />
      <mass value="${wheel_mass}" />
      <inertia ixx="${wheel_Ixx}" ixy="${wheel_Ixy}" ixz="${wheel_Ixz}"
                 iyy="${wheel_Iyy}" iyz="${wheel_Iyz}"
                 izz="${wheel_Izz}" />
    </inertial>
  </link>
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link" />
    <child link="wheel_left_link" />
    <origin xyz="0 0.07 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>


  <!-- Caster wheel front -->
  <link name="caster_front_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://robot_description/meshes/caster_front_link.STL" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.005"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="3.89968128948481E-07 2.40073004698083E-07 0.00219173397061506" rpy="0 0 0" />
      <mass value="1.44379265037903E-06" />
      <inertia ixx="7.23075276010246E-11" ixy="-6.10956883467859E-16" ixz="2.22849693525031E-15"
               iyy="3.8713793085917E-11"  iyz="2.93909858781952E-15"
               izz="1.00967486676306E-10" />
    </inertial>
  </link>
  <joint name="caster_front_joint" type="fixed">
    <origin xyz="0.04755 0 -0.0275" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="caster_front_link" />
    <axis xyz="0 0 0" />
  </joint>
  

  <!-- Caster wheel rear -->
  <link name="caster_rear_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://robot_description/meshes/caster_rear_link.STL" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.005"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="3.8996812895542E-07 2.40073004698083E-07 0.00219173397061509" rpy="0 0 0" />
      <mass value="1.44379265037902E-06" />
      <inertia ixx="7.23075276010246E-11" ixy="-6.10956872363424E-16" ixz="2.22849693527207E-15"
               iyy="3.87137930859167E-11" iyz="2.939098587861E-15"
               izz="1.00967486676306E-10" />
    </inertial>
  </link>
  <joint name="caster_rear_joint" type="fixed">
    <origin xyz="-0.04755 0 -0.0275" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="caster_rear_link" />
    <axis xyz="0 0 0" />
  </joint>


  <!-- IMU sensor -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://bumperbot_description/meshes/imu_link.STL" />
      </geometry>
      <material name="">
        <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://bumperbot_description/meshes/imu_link.STL" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.00552433659106688 0.000168210391520346 0.000514000497342681" rpy="0 0 0" />
      <mass value="0.000528415362211671" />
      <inertia ixx="1.46176048428261E-08" ixy="1.40015117949421E-10" ixz="-1.99633872937403E-12"
               iyy="8.59662482954888E-09" iyz="7.52375112767959E-12"
               izz="2.30279421279312E-08" />
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0.0698986241758014" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="imu_link" />
    <axis xyz="0 0 0" />
  </joint>


  <!-- Ultrasonic sensor 1 -->
  <link name="ultrasonic_1_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>
    <inertia>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1E-5" />
      <inertia ixx="1E-6" ixy="0" ixz="0"
               iyy="1E-6" iyz="0"
               izz="1E-6" />
    </inertia>
  </link>
  <joint name="ultrasonic_1_joint" type="fixed">
    <origin xyz="0.04 0 0.001" rpy="0 0 0" />
    <axis xyz="1 0 0" />
    <parent link="base_link"/>
    <child link="ultrasonic_1_link"/>
  </joint>


  <!-- Ultrasonic sensor 2 -->
  <link name="ultrasonic_2_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>
    <inertia>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1E-5" />
      <inertia ixx="1E-6" ixy="0" ixz="0"
               iyy="1E-6" iyz="0"
               izz="1E-6" />
    </inertia>
  </link>
  <joint name="ultrasonic_2_joint" type="fixed">
    <origin xyz="0.04 0.04 0.001" rpy="0 0 ${30*deg2rad}" />
    <axis xyz="1 0 0" />
    <parent link="base_link"/>
    <child link="ultrasonic_2_link"/>
  </joint>


  <!-- Ultrasonic sensor 3 -->
  <link name="ultrasonic_3_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>
    <inertia>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1E-5" />
      <inertia ixx="1E-6" ixy="0" ixz="0"
               iyy="1E-6" iyz="0"
               izz="1E-6" />
    </inertia>
  </link>
  <joint name="ultrasonic_3_joint" type="fixed">
    <origin xyz="0.04 -0.04 0.001" rpy="0 0 ${-30*deg2rad}" />
    <axis xyz="1 0 0" />
    <parent link="base_link"/>
    <child link="ultrasonic_3_link"/>
  </joint>
  
</robot>
